meta_product_name: "MentorMatch"
meta_title: "MentorMatch"
meta_description: "A Foot in the Door Without a Connection"
meta_image: "logo-text-white.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account" # required for Twitter Cards
